FROM {{IMAGENAME}}

RUN apt-get update && apt-get install -y python-pip python-dev libssl-dev lintian fakeroot dpkg-dev git
RUN pip install --upgrade pip
RUN pip install --upgrade six
RUN pip install cython
RUN pip install py2deb


