#!/bin/bash

IMAGENAME=${2:-"debian:jessie"}
sed "s/{{IMAGENAME}}/${IMAGENAME}/" Dockerfile.templ > Dockerfile
docker build -t py2deb .
rm Dockerfile
mkdir -p pkg
docker run -v `pwd`/pkg:/tmp --rm=true -it  --name py2deb py2deb py2deb -- $1


